# MYSQL
spring.datasource.url= jdbc:mysql://${{ MYSQLUSER }}:${{ MYSQLPASSWORD }}@${{ MYSQLHOST }}:${{ MYSQLPORT }}/${{ MYSQLDATABASE }}
spring.datasource.username= ${{ MYSQLUSER }}
spring.datasource.password= ${{ MYSQLPASSWORD }}

#JPA
spring.jpa.hibernate.ddl-auto= none
spring.jpa.show-sql= true
spring.jpa.open-in-view= true

# THYMELEAF
spring.thymeleaf.cache= false

#IMAGES
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
